name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Preparar carpeta web
        run: |
          mkdir -p www
          cp index.html www/

      - name: Instalar Cordova y Construir APK
        run: |
          npm install -g cordova
          cordova create appcom com.kzr.ventas KzRVentas
          cd appcom
          rm -rf www
          cp -r ../www .
          cordova platform add android
          cordova build android --debug

      - name: Subir ejecutable APK
        uses: actions/upload-artifact@v4
        with:
          name: KzR-Ventas-APK
          path: appcom/platforms/android/app/build/outputs/apk/debug/app-debug.apk
